export const exercises = {
  // Chest
  barbellBenchPress: "Barbell Bench Press",
  dumbbellBenchPress: "Dumbbell Bench Press",
  inclineBarbellBenchPress: "Incline Barbell Bench Press",
  inclineDumbbellBenchPress: "Incline Dumbbell Bench Press",
  declineBarbellBenchPress: "Decline Barbell Bench Press",
  declineDumbbellBenchPress: "Decline Dumbbell Bench Press",
  chestFlyMachine: "Chest Fly Machine",
  chestFlyDumbbell: "Chest Fly Dumbbell",
  pecDeckMachine: "Pec Deck Machine",
  cableCrossovers: "Cable Crossovers",
  pushUp: "Push-Up",
  floorPressDumbbell: "Floor Press (Dumbbell)",
  svendPress: "Svend Press",
  chestDip: "Chest Dip",
  machineChestPress: "Machine Chest Press",

  // Back
  barbellBentOverRows: "Barbell Bent Over Rows",
  dumbbellSingleArmRow: "Dumbbell Single Arm Row",
  pullUps: "Pull Ups",
  chinUps: "Chin Ups",
  latPulldown: "Lat Pulldown",
  seatedCableRow: "Seated Cable Row",
  tBarRow: "T-Bar Row",
  deadlift: "Deadlift",
  goodMornings: "Good Mornings",
  hyperextensions: "Hyperextensions",
  singleArmDumbbellRow: "Single-Arm Dumbbell Row",
  reverseGripBentOverRows: "Reverse Grip Bent-Over Rows",

  // Legs
  barbellSquat: "Barbell Squat",
  deadlift: "Deadlift",
  sumoDeadlift: "Sumo Deadlift",
  legPress: "Leg Press",
  dumbbellLunges: "Dumbbell Lunges",
  squatHackSquatMachine: "Squat (Hack Squat Machine)",
  legCurlsLyingOrSeated: "Leg Curls (Lying or Seated)",
  legExtensions: "Leg Extensions",
  calfRaisesStanding: "Calf Raises (Standing)",
  calfRaisesSeated: "Calf Raises (Seated)",
  romanianDeadlift: "Romanian Deadlift",
  barbellHipThrust: "Barbell Hip Thrust",
  bulgarianSplitSquat: "Bulgarian Split Squat",
  gobletSquat: "Goblet Squat",
  smithMachineSquats: "Smith Machine Squats",
  frontSquats: "Front Squats",
  walkingLunges: "Walking Lunges",
  stepUps: "Step-Ups",
  thighAbductor: "Thigh Abductor",
  sissySquat: "Sissy Squat",

  // Shoulders
  shoulderPressBarbell: "Shoulder Press (Barbell)",
  dumbbellShoulderPress: "Dumbbell Shoulder Press",
  lateralRaises: "Lateral Raises",
  frontDumbbellRaises: "Front Dumbbell Raises",
  rearDeltFly: "Rear Delt Fly",
  shrugsBarbell: "Shrugs (Barbell)",
  shrugsDumbbell: "Shrugs (Dumbbell)",
  facePulls: "Face Pulls",
  arnoldPress: "Arnold Press",
  uprightRow: "Upright Row",
  militaryPress: "Military Press",
  seatedBentOverRearDeltRaise: "Seated Bent-Over Rear Delt Raise",
  standingDumbbellFly: "Standing Dumbbell Fly",

  // Arms
  bicepCurlBarbell: "Bicep Curl (Barbell)",
  bicepCurlDumbbell: "Bicep Curl (Dumbbell)",
  hammerCurlDumbbell: "Hammer Curl (Dumbbell)",
  preacherCurlBarbell: "Preacher Curl (Barbell)",
  tricepPushdown: "Tricep Pushdown",
  skullCrushersEZBar: "Skull Crushers (EZ Bar)",
  dumbbellTricepExtension: "Dumbbell Tricep Extension",
  tricepDips: "Tricep Dips",
  closeGripBenchPress: "Close-Grip Bench Press",
  wideGripBarbellCurl: "Wide-Grip Barbell Curl",
  concentrationCurls: "Concentration Curls",
  zottmanCurl: "Zottman Curl",
  overheadTricepExtension: "Overhead Tricep Extension",
  cableBicepCurl: "Cable Bicep Curl",
  cableTricepKickback: "Cable Tricep Kickback",

  // Abs
  crunches: "Crunches",
  legRaises: "Leg Raises",
  plank: "Plank",
  russianTwist: "Russian Twist",
  hangingLegRaise: "Hanging Leg Raise",
  bicycleCrunches: "Bicycle Crunches",
  mountainClimbers: "Mountain Climbers",
  vUps: "V-Ups",
  abWheelRollout: "Ab Wheel Rollout",
  cableCrunch: "Cable Crunch",
};
