import { exercises } from "../../exercises";
import { exerciseInstructions } from "../../exerciseInstructions";
const getExercisesBBPPLOne = () => {
  return [
    {
      id: "exerciseOne",
      type: "Push",
      typeMobile: "Push",
      weightTag: "",
      name: exercises.barbellBenchPress,
      warmUpSets: 3,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwo",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.militaryPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThree",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.skullCrushersEZBar,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFour",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.fullRomPushUp,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFive",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.tricepPulldownRope,
      warmUpSets: 0,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSix",
      type: "Pull",
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.kneelingSingleArmLatPulldown,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSeven",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.chestSupportedMachineRow,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEight",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.rearDeltFly,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseNine",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.bicepCurlBarbell,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.hammerCurlDumbbell,
      warmUpSets: 0,
      workingSets: 4,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEleven",
      type: "Legs", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.barbellHighbarSquat,
      warmUpSets: 3,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwelve",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.legCurlLying,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThirteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.legExtensions,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFourteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.calfRaisesStanding,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFifteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.cableCrunch,
      warmUpSets: 0,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSixteen",
      type: "Push", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.inclineSmithMachineBenchPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSeventeen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.overheadPressBarbell,
      warmUpSets: 2,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEighteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.chestDip,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseNineteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.egyptianLatRaise,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwenty",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      weightTag: "",
      name: exercises.cableTricepKickback,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyOne",
      type: "Pull", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.singleArmSeatedCableRow,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyTwo",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.landmineRow,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyThree",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.reversePecDec,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyFour",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.twentyOnesBarbell,
      warmUpSets: 1,
      workingSets: 3,
      reps: "21",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyFive",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      weightTag: "",
      name: exercises.bayesianCableCurl,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentySix",
      type: "Legs", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.legPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyseven",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.romanianDeadlift,
      warmUpSets: 2,
      workingSets: 3,
      reps: "6-8",
      RPE: 8,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyEight",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.bulgarianSplitSquat,
      warmUpSets: 0,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyNine",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.calfRaisesSeated,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThirty",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      weightTag: "",
      name: exercises.legRaises,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
  ];
};
const getExercisesBBPPLTwo = () => {
  return [
    // Push Day Exercises
    {
      id: "exerciseOne",
      type: "Push",
      typeMobile: "Push",
      name: exercises.machineChestPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwo",
      type: "",
      typeMobile: "Push",
      name: exercises.dumbbellShoulderPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThree",
      type: "",
      typeMobile: "Push",
      name: exercises.cableCrossovers,
      warmUpSets: 2,
      workingSets: 3,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFour",
      type: "",
      typeMobile: "Push",
      name: exercises.overheadTricepExtension,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFive",
      type: "",
      typeMobile: "Push",
      name: exercises.svendPress,
      warmUpSets: 0,
      workingSets: 3,
      reps: "15-20",
      RPE: 7,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Pull Day Exercises
    {
      id: "exerciseSix",
      type: "Pull",
      typeMobile: "Pull",
      name: exercises.seatedCableRow,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSeven",
      type: "",
      typeMobile: "Pull",
      name: exercises.pullUps,
      warmUpSets: 1,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEight",
      type: "",
      typeMobile: "Pull",
      name: exercises.reverseGripBentOverRows,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseNine",
      type: "",
      typeMobile: "Pull",
      name: exercises.facePulls,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 7,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTen",
      type: "",
      typeMobile: "Pull",
      name: exercises.hammerCurlDumbbell,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Legs Day Exercises
    {
      id: "exerciseEleven",
      type: "Legs",
      typeMobile: "Legs",
      name: exercises.frontSquats,
      warmUpSets: 3,
      workingSets: 3,
      reps: "5-7",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwelve",
      type: "",
      typeMobile: "Legs",
      name: exercises.romanianDeadlift,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThirteen",
      type: "",
      typeMobile: "Legs",
      name: exercises.legPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 8,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFourteen",
      type: "",
      typeMobile: "Legs",
      name: exercises.calfRaisesSeated,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFifteen",
      type: "",
      typeMobile: "Legs",
      name: exercises.legCurlLying,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Push Day 2
    {
      id: "exerciseSixteen",
      type: "Push",
      typeMobile: "Push",
      name: exercises.dumbbellBenchPress,
      warmUpSets: 3,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSeventeen",
      type: "",
      typeMobile: "Push",
      name: exercises.lateralRaises,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEighteen",
      type: "",
      typeMobile: "Push",
      name: exercises.closeGripBenchPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseNineteen",
      type: "",
      typeMobile: "Push",
      name: exercises.tricepDips,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwenty",
      type: "",
      typeMobile: "Push",
      name: exercises.arnoldPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Pull Day 2
    {
      id: "exerciseTwentyOne",
      type: "Pull",
      typeMobile: "Pull",
      name: exercises.deadlift,
      warmUpSets: 3,
      workingSets: 3,
      reps: "5-7",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyTwo",
      type: "",
      typeMobile: "Pull",
      name: exercises.chinUps,
      warmUpSets: 2,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyThree",
      type: "",
      typeMobile: "Pull",
      name: exercises.barbellBentOverRows,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyFour",
      type: "",
      typeMobile: "Pull",
      name: exercises.rearDeltFly,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 7,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyFive",
      type: "",
      typeMobile: "Pull",
      name: exercises.preacherCurlBarbell,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Legs Day 2
    {
      id: "exerciseTwentySix",
      type: "Legs",
      typeMobile: "Legs",
      name: exercises.squatHackSquatMachine,
      warmUpSets: 3,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentySeven",
      type: "",
      typeMobile: "Legs",
      name: exercises.walkingLunges,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12 per leg",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyEight",
      type: "",
      typeMobile: "Legs",
      name: exercises.stepUps,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12 per leg",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyNine",
      type: "",
      typeMobile: "Legs",
      name: exercises.calfRaisesStanding,
      warmUpSets: 2,
      workingSets: 4,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThirty",
      type: "",
      typeMobile: "Legs",
      name: exercises.abWheelRollout,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1",
      exerciseInfo: "",
      alternativeExercise: "",
    },
  ];
};
const getExerciseBBUpperLower = () => {
  return [
    //Upper 1
    {
      id: "exerciseOne",
      type: "Upper (Day 1)",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.dumbbellBenchPress,
      warmUpSets: 3,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.dumbbellBenchPress,
      alternativeExercise: "Barbell Bench Press",
    },
    {
      id: "exerciseTwo",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.smithMachineShoulderPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.smithMachineShoulderPress,
      alternativeExercise: "Machine Shoulder Press",
    },
    {
      id: "exerciseThree",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.chestSupportedMachineRow,
      warmUpSets: 2,
      workingSets: 4,
      reps: "8-10",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.chestSupportedMachineRow,
      alternativeExercise: "Seated Cable Row",
    },
    {
      id: "exerciseFour",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.cableTricepKickback,
      warmUpSets: 2,
      workingSets: 4,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.cableTricepKickback,
      alternativeExercise: "Dumbbell Tricep Kickbacks",
    },
    {
      id: "exerciseFive",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.bicepCurlBarbell,
      warmUpSets: 2,
      workingSets: 4,
      reps: "10-12",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.bicepCurlBarbell,
      alternativeExercise: "Dumbbell Bicep Curl",
    },
    {
      id: "exerciseSix",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.pecDeckMachinePartials,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.pecDeckMachine,
      alternativeExercise: "Dumbbell Bicep Curl",
    },
    //Lower 1
    {
      id: "exerciseSeven",
      type: "Lower (Day 2)",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.squatHackSquatMachine,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.squatHackSquatMachine,
      alternativeExercise: "Smith Machine Squat",
    },
    {
      id: "exerciseEight",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.romainainDeadliftDB,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.romainainDeadliftDB,
      alternativeExercise: "Romanian Deadlift Barbell",
    },
    {
      id: "exerciseNine",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.legCurlSeated,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.legCurlSeated,
      alternativeExercise: "Laying Leg Curl",
    },
    {
      id: "exerciseTen",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.calfRaisesStanding,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.calfRaisesStanding,
      alternativeExercise: "Seated Calf Raises",
    },
    {
      id: "exerciseEleven",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.abCrunchMachine,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1",
      exerciseInfo: exerciseInstructions.abCrunchMachine,
      alternativeExercise: "Weighted Ab Crunch",
    },
    //Upper 2
    {
      id: "exerciseTwelve",
      type: "Upper (Day 3)",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.machineChestPress,
      warmUpSets: 3,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.machineChestPress,
      alternativeExercise: "Smith Machine Bench Press",
    },
    {
      id: "exerciseThirteen",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.machineShoulderPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.machineShoulderPress,
      alternativeExercise: "Dumbbell Press",
    },
    {
      id: "exerciseFourteen",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.latPulldown,
      warmUpSets: 2,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.latPulldown,
      alternativeExercise: "Single Arm Cable Pulldown",
    },
    {
      id: "exerciseFifteen",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.skullCrushersEZBar,
      warmUpSets: 2,
      workingSets: 4,
      reps: "10-12",
      RPE: 8,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.skullCrushersEZBar,
      alternativeExercise: "Dumbbell Skull Crushers",
    },
    {
      id: "exerciseSixteen",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.seatedInclineDumbbellCurl,
      warmUpSets: 2,
      workingSets: 4,
      reps: "10-12",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.seatedInclineDumbbellCurl,
      alternativeExercise: "Dumbbell Bicep Curl",
    },
    {
      id: "exerciseSeventeen",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.chinUps,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.chinUps,
      alternativeExercise: "Neutral Grip Pull-Ups",
    },
    {
      id: "exerciseEighteen",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.shrugsDumbbell,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.shrugsDumbbell,
      alternativeExercise: "Cable Shrug",
    },
    {
      id: "exerciseNineteen",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.tricepPulldownRope,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.tricepPulldownRope,
      alternativeExercise: "Tricep Pulldown (Bar)",
    },
    //Lower 2
    {
      id: "exerciseTwenty",
      type: "Lower (Day 4)",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.legPress,
      warmUpSets: 1,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "2-3",
      exerciseInfo: exerciseInstructions.legPress,
      alternativeExercise: "High-Bar Back Squat",
    },
    {
      id: "exerciseTwentyOne",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.legCurlLying,
      warmUpSets: 1,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.legCurlLying,
      alternativeExercise: "Seated Leg Curl",
    },
    {
      id: "exerciseTwentyTwo",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.calfRaisesSeated,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.calfRaisesSeated,
      alternativeExercise: "Calf Raises Standing",
    },
    {
      id: "exerciseTwentyThree",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.legExtensions,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.legExtensions,
      alternativeExercise: "",
    },
    //Upper 3
    {
      id: "exerciseTwentyFour",
      type: "Upper (Day 5)",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.inclineSmithMachineBenchPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.inclineSmithMachineBenchPress,
      alternativeExercise: "Incline Dumbbell Press",
    },
    {
      id: "exerciseTwentyFive",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.overheadPressBarbell,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.overheadPressBarbell,
      alternativeExercise: "overhead Dumbbell Press",
    },
    {
      id: "exerciseTwentySix",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.barbellBentOverRows,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.barbellBentOverRows,
      alternativeExercise: "overhead Dumbbell Press",
    },
    {
      id: "exerciseTwentySeven",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.closeGripBenchPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.closeGripBenchPress,
      alternativeExercise: "V-Bar Pushdown",
    },
    {
      id: "exerciseTwentyEight",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.bayesianCableCurl,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.bayesianCableCurl,
      alternativeExercise: "Cable Curl",
    },
    {
      id: "exerciseTwentyNine",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.facePulls,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.facePulls,
      alternativeExercise: "Bent Over Raises",
    },
    {
      id: "exerciseThirty",
      type: "",
      typeMobile: "Upper",
      weightTag: "",
      name: exercises.seatedCableRow,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.seatedCableRow,
      alternativeExercise: "Dumbbell Row",
    },
    //Lower 3
    {
      id: "exerciseThirtyOne",
      type: "Lower (Day 6)",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.deadlift,
      warmUpSets: 3,
      workingSets: 4,
      reps: "6-8",
      RPE: 8,
      oneRepMax: "",
      rest: "2-3",
      exerciseInfo: exerciseInstructions.deadlift,
      alternativeExercise: "Rack Pulls",
    },
    {
      id: "exerciseThirtyTwo",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.bulgarianSplitSquat,
      warmUpSets: 3,
      workingSets: 4,
      reps: "8-19",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.bulgarianSplitSquat,
      alternativeExercise: "Split Sqiats",
    },
    {
      id: "exerciseThirtyThree",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.barbellHipThrust,
      warmUpSets: 2,
      workingSets: 4,
      reps: "8-10",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.barbellHipThrust,
      alternativeExercise: "Split Sqiats",
    },
    {
      id: "exerciseThirtyFour",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.calfRaisesStanding,
      warmUpSets: 1,
      workingSets: 4,
      reps: "8-10",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.calfRaisesStanding,
      alternativeExercise: "Seated Calf Raises",
    },
    {
      id: "exerciseThirtyFive",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.hangingLegRaise,
      warmUpSets: 1,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.hangingLegRaise,
      alternativeExercise: "laying Leg Raises",
    },
    {
      id: "exerciseThirtySix",
      type: "",
      typeMobile: "Lower",
      weightTag: "",
      name: exercises.russianTwist,
      warmUpSets: 1,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      oneRepMax: "",
      rest: "1-2",
      exerciseInfo: exerciseInstructions.russianTwist,
      alternativeExercise: "Woodchopper",
    },
  ];
};
const getExercisesBBHomeWithWeights = () => {
  return [
    {
      id: "exerciseOne",
      type: "Full Body (Day 1)",
      typeMobile: "Full Body",
      weightTag: "",
      name: exercises.floorPressDumbbell,
      warmUpSets: 2,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.floorPressDumbbell,
      alternativeExercise: "Push-Up",
    },
    {
      id: "exerciseTwo",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.gobletSquat,
      warmUpSets: 2,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.gobletSquat,
      alternativeExercise: "Bodyweight Squat",
    },
    {
      id: "exerciseThree",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.bicepCurlDumbbell,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.bicepCurlDumbbell,
      alternativeExercise: "Barbell Curl",
    },
    {
      id: "exerciseFour",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "Bodyweight",
      name: exercises.closeGripPushup,
      warmUpSets: 0,
      workingSets: 5,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.closeGripPushup,
      alternativeExercise: "",
    },
    {
      id: "exerciseFive",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.alternatingDumbbellShoulderPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.alternatingDumbbellShoulderPress,
      alternativeExercise: "Arnold Press",
    },
    {
      id: "exerciseSix",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.dumbbellSingleArmRow,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.dumbbellSingleArmRow,
      alternativeExercise: "Helms Row",
    },
    {
      id: "exerciseSeven",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.dumbellStandingCalfRaises,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.dumbellStandingCalfRaises,
      alternativeExercise: "Standing Calf Raises (Bodyweight)",
    },
    {
      id: "exerciseEight",
      type: "Full Body (Day 2)",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.floorChestFlyDumbbel,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.floorChestFlyDumbbel,
      alternativeExercise: "Chest Fly Dumbbells (Bench)",
    },
    {
      id: "exerciseNine",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.gluteBridge,
      warmUpSets: 0,
      workingSets: 4,
      reps: "15-20",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.gluteBridge,
      alternativeExercise: "Glute Bridge Barbell Or Dumbbell",
    },
    {
      id: "exerciseTen",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.romainainDeadliftDB,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.romainainDeadliftDB,
      alternativeExercise: "Romanian Deadlift (Barbell)",
    },
    {
      id: "exerciseEleven",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.hammerCurlDumbbell,
      warmUpSets: 1,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.hammerCurlDumbbell,
      alternativeExercise: "Bicep Curl",
    },
    {
      id: "exerciseTwelve",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.singleArmDumbbellTricepExtension,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.singleArmDumbbellTricepExtension,
      alternativeExercise: "Dumbbell Skull Crusher",
    },
    {
      id: "exerciseThirteen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.shrugsDumbbell,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.shrugsDumbbell,
      alternativeExercise: "Laying side down Lateral Raises",
    },
    {
      id: "exerciseFourteen",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.crunchesWeighted,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "30sec",
      exerciseInfo: exerciseInstructions.crunchesWeighted,
      alternativeExercise: "Laying Leg Raises",
    },
    {
      id: "exerciseFifteen",
      type: "Full Body (Day 3)",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.declinePushUp,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.declinePushUp,
      alternativeExercise: "Incline Dumbbell Bench Press",
    },
    {
      id: "exerciseSixteen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.bulgarianSplitSquat,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "2-3",
      exerciseInfo: exerciseInstructions.bulgarianSplitSquat,
      alternativeExercise: "Lunges",
    },
    {
      id: "exerciseSeventeen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.zottmanCurl,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.zottmanCurl,
      alternativeExercise: "Reverse Bicep Curl",
    },
    {
      id: "exerciseEighteen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.dumbbellTricepKickbacks,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.dumbbellTricepKickbacks,
      alternativeExercise: "Skull Crushers (Dumbbell)",
    },
    {
      id: "exerciseNineteen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.dumbbellPulloverFloor,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.dumbbellPulloverFloor,
      alternativeExercise: "Dumbbell Dead Row",
    },
    {
      id: "exerciseTwenty",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.frontDumbbellRaises,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.frontDumbbellRaises,
      alternativeExercise: "Arnold Press",
    },
    {
      id: "exerciseTwentyOne",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.lateralRaises,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.lateralRaises,
      alternativeExercise: "Laying side down Lateral Raises",
    },
    {
      id: "exerciseTwentyTwo",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.jackknifeSitUp,
      warmUpSets: 2,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: exerciseInstructions.jackknifeSitUp,
      alternativeExercise: "Coccon",
    },
  ];
};

export {
  getExercisesBBPPLOne,
  getExercisesBBPPLTwo,
  getExerciseBBUpperLower,
  getExercisesBBHomeWithWeights,
};
