import { exercises } from "../../exercises";
const getExercisesBBPPLOne = () => {
  return [
    {
      id: "exerciseOne",
      type: "Push",
      typeMobile: "Push",
      name: exercises.barbellBenchPress,
      warmUpSets: 3,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwo",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.militaryPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThree",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.skullCrushersEZBar,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFour",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.fullRomPushUp,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFive",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.tricepPulldownRope,
      warmUpSets: 0,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSix",
      type: "Pull",
      typeMobile: "Pull",
      name: exercises.kneelingSingleArmLatPulldown,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSeven",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.chestSupportedMachineRow,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEight",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.rearDeltFly,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseNine",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.bicepCurlBarbell,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.hammerCurlDumbbell,
      warmUpSets: 0,
      workingSets: 4,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEleven",
      type: "Legs", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.barbellHighbarSquat,
      warmUpSets: 3,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwelve",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.legCurlLying,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThirteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.legExtensions,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFourteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.calfRaisesStanding,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFifteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.cableCrunch,
      warmUpSets: 0,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSixteen",
      type: "Push", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.inclineSmithMachineBenchPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSeventeen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.overheadPressBarbell,
      warmUpSets: 2,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEighteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.chestDip,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseNineteen",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.egyptianLatRaise,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwenty",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Push",
      name: exercises.cableTricepKickback,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyOne",
      type: "Pull", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.singleArmSeatedCableRow,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyTwo",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.meadowsRow,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyThree",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.reversePecDec,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyFour",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.twentyOnesBarbell,
      warmUpSets: 1,
      workingSets: 3,
      reps: "21",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyFive",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Pull",
      name: exercises.bayesianCableCurl,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentySix",
      type: "Legs", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.legPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyseven",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.romanianDeadlift,
      warmUpSets: 2,
      workingSets: 3,
      reps: "6-8",
      RPE: 8,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyEight",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.bulgarianSplitSquat,
      warmUpSets: 0,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyNine",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.calfRaisesSeated,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThirty",
      type: "", // Leave type empty for subsequent rows that share the same type
      typeMobile: "Legs",
      name: exercises.legRaises,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
  ];
};
const getExercisesBBPPLTwo = () => {
  return [
    // Push Day Exercises
    {
      id: "exerciseOne",
      type: "Push",
      typeMobile: "Push",
      name: exercises.machineChestPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwo",
      type: "",
      typeMobile: "Push",
      name: exercises.dumbbellShoulderPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThree",
      type: "",
      typeMobile: "Push",
      name: exercises.cableCrossovers,
      warmUpSets: 2,
      workingSets: 3,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFour",
      type: "",
      typeMobile: "Push",
      name: exercises.overheadTricepExtension,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFive",
      type: "",
      typeMobile: "Push",
      name: exercises.svendPress,
      warmUpSets: 0,
      workingSets: 3,
      reps: "15-20",
      RPE: 7,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Pull Day Exercises
    {
      id: "exerciseSix",
      type: "Pull",
      typeMobile: "Pull",
      name: exercises.seatedCableRow,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSeven",
      type: "",
      typeMobile: "Pull",
      name: exercises.pullUps,
      warmUpSets: 1,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEight",
      type: "",
      typeMobile: "Pull",
      name: exercises.reverseGripBentOverRows,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseNine",
      type: "",
      typeMobile: "Pull",
      name: exercises.facePulls,
      warmUpSets: 1,
      workingSets: 3,
      reps: "12-15",
      RPE: 7,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTen",
      type: "",
      typeMobile: "Pull",
      name: exercises.hammerCurlDumbbell,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Legs Day Exercises
    {
      id: "exerciseEleven",
      type: "Legs",
      typeMobile: "Legs",
      name: exercises.frontSquats,
      warmUpSets: 3,
      workingSets: 3,
      reps: "5-7",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwelve",
      type: "",
      typeMobile: "Legs",
      name: exercises.romanianDeadlift,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThirteen",
      type: "",
      typeMobile: "Legs",
      name: exercises.legPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 8,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFourteen",
      type: "",
      typeMobile: "Legs",
      name: exercises.calfRaisesSeated,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFifteen",
      type: "",
      typeMobile: "Legs",
      name: exercises.legCurlLying,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Push Day 2
    {
      id: "exerciseSixteen",
      type: "Push",
      typeMobile: "Push",
      name: exercises.dumbbellBenchPress,
      warmUpSets: 3,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseSeventeen",
      type: "",
      typeMobile: "Push",
      name: exercises.lateralRaises,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseEighteen",
      type: "",
      typeMobile: "Push",
      name: exercises.closeGripBenchPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseNineteen",
      type: "",
      typeMobile: "Push",
      name: exercises.tricepDips,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwenty",
      type: "",
      typeMobile: "Push",
      name: exercises.arnoldPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Pull Day 2
    {
      id: "exerciseTwentyOne",
      type: "Pull",
      typeMobile: "Pull",
      name: exercises.deadlift,
      warmUpSets: 3,
      workingSets: 3,
      reps: "5-7",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyTwo",
      type: "",
      typeMobile: "Pull",
      name: exercises.chinUps,
      warmUpSets: 2,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyThree",
      type: "",
      typeMobile: "Pull",
      name: exercises.barbellBentOverRows,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyFour",
      type: "",
      typeMobile: "Pull",
      name: exercises.rearDeltFly,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 7,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyFive",
      type: "",
      typeMobile: "Pull",
      name: exercises.preacherCurlBarbell,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    // Legs Day 2
    {
      id: "exerciseTwentySix",
      type: "Legs",
      typeMobile: "Legs",
      name: exercises.squatHackSquatMachine,
      warmUpSets: 3,
      workingSets: 3,
      reps: "6-8",
      RPE: 9,
      rest: "2-3",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentySeven",
      type: "",
      typeMobile: "Legs",
      name: exercises.walkingLunges,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12 per leg",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyEight",
      type: "",
      typeMobile: "Legs",
      name: exercises.stepUps,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12 per leg",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseTwentyNine",
      type: "",
      typeMobile: "Legs",
      name: exercises.calfRaisesStanding,
      warmUpSets: 2,
      workingSets: 4,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseThirty",
      type: "",
      typeMobile: "Legs",
      name: exercises.abWheelRollout,
      warmUpSets: 1,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1",
      exerciseInfo: "",
      alternativeExercise: "",
    },
  ];
};
const getExercisesBBHomeWithWeights = () => {
  return [
    {
      id: "exerciseOne",
      type: "Full Body (Day 1)",
      typeMobile: "Full Body",
      weightTag: "",
      name: exercises.floorPressDumbbell,
      warmUpSets: 2,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/dumbbell-floor-press",
      alternativeExercise: "Push-Up",
    },
    {
      id: "exerciseTwo",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.gobletSquat,
      warmUpSets: 2,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/dumbbell-goblet-squat",
      alternativeExercise: "Bodyweight Squat",
    },
    {
      id: "exerciseThree",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.bicepCurlDumbbell,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 9,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/dumbbell-bicep-curl",
      alternativeExercise: "Barbell Curl",
    },
    {
      id: "exerciseFour",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "Bodyweight",
      name: exercises.closeGripPushup,
      warmUpSets: 0,
      workingSets: 5,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo: "",
      alternativeExercise: "",
    },
    {
      id: "exerciseFive",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.alternatingDumbbellShoulderPress,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/standing-alternating-dumbbell-press",
      alternativeExercise: "Arnold Press",
    },
    {
      id: "exerciseSix",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.dumbbellSingleArmRow,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/one-arm-dumbbell-row",
      alternativeExercise: "Helms Row",
    },
    {
      id: "exerciseSeven",
      type: "",
      typeMobile: "Full Body (Day 1)",
      weightTag: "",
      name: exercises.dumbellStandingRaises,
      warmUpSets: 1,
      workingSets: 4,
      reps: "12-15",
      RPE: 8,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/standing-dumbbell-calf-raise",
      alternativeExercise: "Standing Calf Raises (Bodyweight)",
    },
    {
      id: "exerciseEight",
      type: "Full Body (Day 2)",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.floorChestFlyDumbbel,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/dumbbell-fix-dumbbell-floor-chest-fly",
      alternativeExercise: "Chest Fly Dumbbells (Bench)",
    },
    {
      id: "exerciseNine",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.gluteBridge,
      warmUpSets: 0,
      workingSets: 4,
      reps: "15-20",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "https://www.bodybuilding.com/exercises/butt-lift-bridge",
      alternativeExercise: "Glute Bridge Barbell Or Dumbbell",
    },
    {
      id: "exerciseTen",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.romainainDeadliftDB,
      warmUpSets: 2,
      workingSets: 3,
      reps: "8-10",
      RPE: 9,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/romanian-deadlift-with-dumbbells",
      alternativeExercise: "Romanian Deadlift (Barbell)",
    },
    {
      id: "exerciseEleven",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.hammerCurlDumbbell,
      warmUpSets: 1,
      workingSets: 4,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo: "https://www.bodybuilding.com/exercises/hammer-curls",
      alternativeExercise: "Bicep Curl",
    },
    {
      id: "exerciseTwelve",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.singleArmDumbbellTricepExtension,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 9,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/dumbbell-one-arm-triceps-extension",
      alternativeExercise: "Dumbbell Skull Crusher",
    },
    {
      id: "exerciseThirteen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.shrugsDumbbell,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "https://www.bodybuilding.com/exercises/dumbbell-shrug",
      alternativeExercise: "Laying side down Lateral Raises",
    },
    {
      id: "exerciseFourteen",
      type: "",
      typeMobile: "Full Body (Day 2)",
      weightTag: "",
      name: exercises.crunchesWeighted,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "30sec",
      exerciseInfo: "https://www.bodybuilding.com/exercises/weighted-crunches",
      alternativeExercise: "Laying Leg Raises",
    },
    {
      id: "exerciseFifteen",
      type: "Full Body (Day 3)",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.declinePushUp,
      warmUpSets: 0,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "https://www.bodybuilding.com/exercises/decline-push-up",
      alternativeExercise: "Incline Dumbbell Bench Press",
    },
    {
      id: "exerciseSixteen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.bulgarianSplitSquat,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "2-3",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/split-squat-with-dumbbells",
      alternativeExercise: "Lunges",
    },
    {
      id: "exerciseSeventeen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.zottmanCurl,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "https://www.bodybuilding.com/exercises/zottman-curl",
      alternativeExercise: "Reverse Bicep Curl",
    },
    {
      id: "exerciseEighteen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.dumbbellTricepKickbacks,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/tricep-dumbbell-kickback",
      alternativeExercise: "Skull Crushers (Dumbbell)",
    },
    {
      id: "exerciseNineteen",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.dumbbellPulloverFloor,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/dumbbell-fix-dumbbell-pull-over",
      alternativeExercise: "Dumbbell Dead Row",
    },
    {
      id: "exerciseTwenty",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.frontDumbbellRaises,
      warmUpSets: 1,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo:
        "https://www.bodybuilding.com/exercises/dumbbell-fix-dumbbell-pull-over",
      alternativeExercise: "Arnold Press",
    },
    {
      id: "exerciseTwentyOne",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.lateralRaises,
      warmUpSets: 2,
      workingSets: 3,
      reps: "10-12",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "https://www.bodybuilding.com/exercises/side-lateral-raise",
      alternativeExercise: "Laying side down Lateral Raises",
    },
    {
      id: "exerciseTwentyTwo",
      type: "",
      typeMobile: "Full Body (Day 3)",
      weightTag: "",
      name: exercises.vUps,
      warmUpSets: 2,
      workingSets: 3,
      reps: "12-15",
      RPE: 10,
      rest: "1-2",
      exerciseInfo: "https://www.bodybuilding.com/exercises/jackknife-sit-up",
      alternativeExercise: "Coccon",
    },
  ];
};

export {
  getExercisesBBPPLOne,
  getExercisesBBPPLTwo,
  getExercisesBBHomeWithWeights,
};
