export const exercises = {
  // Chest
  barbellBenchPress: "Barbell Bench Press",
  dumbbellBenchPress: "Dumbbell Bench Press",
  inclineBarbellBenchPress: "Incline Barbell Bench Press",
  inclineDumbbellBenchPress: "Incline Dumbbell Bench Press",
  declineBarbellBenchPress: "Decline Barbell Bench Press",
  declineDumbbellBenchPress: "Decline Dumbbell Bench Press",
  inclineSmithMachineBenchPress: "Incline Smith Machine Bench Press",
  smithMachineBenchPress: "Smith Machine Bench Press",
  chestFlyMachine: "Chest Fly (Machine)",
  chestFlyDumbbell: "Chest Fly (Dumbbells)",
  floorChestFlyDumbbel: "Floor Chest Fly (Dumbbells)",
  pecDeckMachine: "Pec Deck Machine",
  cableCrossovers: "Cable Crossovers",
  fullRomPushUp: "Full ROM Push-Up",
  declinePushUp: "Decline Push-UP",
  floorPressDumbbell: "Floor Press (Dumbbell)",
  svendPress: "Svend Press",
  chestDip: "Chest Dip",
  machineChestPress: "Machine Chest Press",

  // Back
  barbellBentOverRows: "Barbell Bent Over Rows",
  dumbbellSingleArmRow: "Dumbbell Single Arm Row",
  kneelingSingleArmLatPulldown: "Kneeling Single Arm Lat Pulldown",
  pullUps: "Pull Ups",
  chinUps: "Chin Ups",
  latPulldown: "Lat Pulldown",
  seatedCableRow: "Seated Cable Row",
  singleArmSeatedCableRow: "Single Arm Seated Cable Row",
  chestSupportedMachineRow: "Chest Supported Machine Row",
  tBarRow: "T-Bar Row",
  deadlift: "Deadlift",
  goodMornings: "Good Mornings",
  hyperextensions: "Hyperextensions",
  singleArmDumbbellRow: "Single-Arm Dumbbell Row",
  reverseGripBentOverRows: "Reverse Grip Bent-Over Rows",
  meadowsRow: "Meadows Row",
  baerbellRow: "Barbell Row",
  dumbbellPullover: "Dumbbell Pullover",
  dumbbellPulloverFloor: "Dumbbell Pullover (Floor)",

  // Legs
  barbellLowbarSquat: "Barbell Squat (Low Bar)",
  barbellHighbarSquat: "Barbell Squat (High Bar)",
  sumoDeadlift: "Sumo Deadlift",
  legPress: "Leg Press",
  dumbbellLunges: "Dumbbell Lunges",
  squatHackSquatMachine: "Squat (Hack Squat Machine)",
  legCurlLying: "Leg Curls (Lying)",
  legCurlSeated: "Leg Curls (Seated)",
  legExtensions: "Leg Extensions",
  calfRaisesStanding: "Calf Raises (Standing)",
  calfRaisesSeated: "Calf Raises (Seated)",
  dumbellStandingRaises: "Standing Dumbbell Cald Raises",
  romanianDeadlift: "Romanian Deadlift",
  romainainDeadliftDB: "Romainain Deadlift (Dumbbells)",
  barbellHipThrust: "Barbell Hip Thrust",
  bulgarianSplitSquat: "Bulgarian Split Squat",
  gobletSquat: "Goblet Squat",
  smithMachineSquats: "Smith Machine Squats",
  frontSquats: "Front Squats",
  walkingLunges: "Walking Lunges",
  stepUps: "Step-Ups",
  thighAbductor: "Thigh Abductor",
  sissySquat: "Sissy Squat",
  gluteBridgeBarbell: "Barbell Glute Bridge",
  gluteBridge: "Glute Bridge",

  // Shoulders
  overheadPressBarbell: "Shoulder Press (Barbell)",
  dumbbellShoulderPress: "Dumbbell Shoulder Press",
  alternatingDumbbellShoulderPress: "Alternating Dumbbell Shoulder Press",
  lateralRaises: "Lateral Raises",
  frontDumbbellRaises: "Front Raises (Dumbbells)",
  rearDeltFly: "Rear Delt Fly",
  reversePecDec: "Reverse Pec Dec Fly",
  shrugsBarbell: "Shrugs (Barbell)",
  shrugsDumbbell: "Shrugs (Dumbbell)",
  facePulls: "Face Pulls",
  arnoldPress: "Arnold Press",
  uprightRow: "Upright Row",
  militaryPress: "Military Press",
  seatedBentOverRearDeltRaise: "Seated Bent-Over Rear Delt Raise",
  standingDumbbellFly: "Standing Dumbbell Fly",
  egyptianLatRaise: "Egyptian Lat Raise",
  bentOverRearDeltRow: "Bent-over Rear Delt Row (Dumbbells)",

  //Triceps
  tricepPulldownRope: "Tricep Push-down (Rope)",
  tricepPushdownStraightbar: "Tricep Push-down (Straight Bar)",
  tricepPushdownVBar: "Tricep Push-down (V Bar)",
  skullCrushersEZBar: "Skull Crushers (EZ Bar)",
  dumbbellTricepExtension: "Dumbbell Tricep Extension",
  tricepDips: "Tricep Dips",
  closeGripBenchPress: "Close-Grip Bench Press",
  cableTricepKickback: "Tricep Kickbacks (Cable)",
  dumbbellTricepKickbacks: "Tricep Kickbacks (Dumbbell)",
  overheadTricepExtension: "Overhead Tricep Extension",
  closeGripPushup: "Close Stance Pushup",
  singleArmDumbbellTricepExtension: "Single Arm Tricep Extension (Dumbbells)",

  // Biceps
  bicepCurlBarbell: "Bicep Curl (Barbell)",
  bicepCurlDumbbell: "Bicep Curl (Dumbbell)",
  twentyOnesBarbell: "21's Barbell Curl",
  twentyOnesDumbbell: "21's Dumbbell Curl",
  bayesianCableCurl: "Bayesian Cable Curl",
  hammerCurlDumbbell: "Hammer Curl (Dumbbell)",
  preacherCurlBarbell: "Preacher Curl (Barbell)",
  wideGripBarbellCurl: "Wide-Grip Barbell Curl",
  concentrationCurls: "Concentration Curls",
  zottmanCurl: "Zottman Curl",
  cableBicepCurl: "Cable Bicep Curl",

  // Abs
  crunches: "Crunches",
  crunchesWeighted: "Weighted Crunches",
  legRaises: "Leg Raises",
  plank: "Plank",
  russianTwist: "Russian Twist",
  hangingLegRaise: "Hanging Leg Raise",
  bicycleCrunches: "Bicycle Crunches",
  mountainClimbers: "Mountain Climbers",
  vUps: "V-Ups",
  abWheelRollout: "Ab Wheel Rollout",
  cableCrunch: "Cable Crunch",
  cocoon: "Cocoon",
};
