export const exercises = {
  // Chest
  barbellBenchPress: "Barbell Bench Press",
  dumbbellBenchPress: "Dumbbell Bench Press",
  inclineBarbellBenchPress: "Incline Barbell Bench Press",
  inclineDumbbellBenchPress: "Incline Dumbbell Bench Press",
  declineBarbellBenchPress: "Decline Barbell Bench Press",
  declineDumbbellBenchPress: "Decline Dumbbell Bench Press",
  inclineSmithMachineBenchPress: "Incline Smith Machine Bench Press",
  smithMachineBenchPress: "Smith Machine Bench Press",
  chestFlyMachine: "Chest Fly (Machine)",
  chestFlyDumbbell: "Chest Fly (Dumbbells)",
  floorChestFlyDumbbel: "Floor Chest Fly (Dumbbells)",
  pecDeckMachine: "Pec Deck Machine",
  pecDeckMachinePartials: "Pec Deck Machine (Alternating Partial Reps",
  cableCrossovers: "Cable Crossovers",
  fullRomPushUp: "Full ROM Push-Up",
  declinePushUp: "Decline Push-UP",
  floorPressDumbbell: "Floor Press (Dumbbell)",
  svendPress: "Svend Press",
  chestDip: "Chest Dip",
  machineChestPress: "Machine Chest Press",

  // Back
  barbellBentOverRows: "Barbell Bent Over Rows",
  dumbbellSingleArmRow: "Dumbbell Single Arm Row",
  kneelingSingleArmLatPulldown: "Kneeling Single Arm Lat Pulldown",
  pullUps: "Pull Ups",
  chinUps: "Chin Ups",
  latPulldown: "Lat Pulldown",
  seatedCableRow: "Seated Cable Row",
  singleArmSeatedCableRow: "Single Arm Seated Cable Row",
  chestSupportedMachineRow: "Chest Supported Machine Row",
  tBarRow: "T-Bar Row",
  deadlift: "Deadlift",
  goodMornings: "Good Mornings",
  hyperextensions: "Hyperextensions",
  singleArmDumbbellRow: "Single-Arm Dumbbell Row",
  reverseGripBentOverRows: "Reverse Grip Bent-Over Rows",
  landmineRow: "Meadows Row",
  baerbellRow: "Barbell Row",
  dumbbellPullover: "Dumbbell Pullover",
  dumbbellPulloverFloor: "Dumbbell Floor Pullover",

  // Legs
  barbellLowbarSquat: "Barbell Squat (Low Bar)",
  barbellHighbarSquat: "Barbell Squat (High Bar)",
  sumoDeadlift: "Sumo Deadlift",
  legPress: "Leg Press",
  dumbbellLunges: "Dumbbell Lunges",
  squatHackSquatMachine: "Hack Squat",
  legCurlLying: "Leg Curls (Lying)",
  legCurlSeated: "Leg Curls (Seated)",
  legExtensions: "Leg Extensions",
  calfRaisesStanding: "Calf Raises (Standing)",
  calfRaisesSeated: "Calf Raises (Seated)",
  calfRaiseLegPress: "Calf Raises (Leg Press Machine)",
  dumbellStandingCalfRaises: "Standing Dumbbell Calf Raises",
  romanianDeadlift: "Barbell Romanian Deadlift",
  romainainDeadliftDB: "Dumbbell Romainain Deadlift",
  barbellHipThrust: "Barbell Hip Thrust",
  bulgarianSplitSquat: "Bulgarian Split Squat",
  gobletSquat: "Goblet Squat",
  smithMachineSquats: "Smith Machine Squats",
  frontSquats: "Front Squats",
  walkingLunges: "Walking Lunges",
  stepUps: "Step-Ups",
  thighAbductor: "Thigh Abductor",
  sissySquat: "Sissy Squat",
  gluteBridgeBarbell: "Barbell Glute Bridge",
  gluteBridge: "Glute Bridge",

  // Shoulders
  overheadPressBarbell: "Barbell Shoulder Press",
  dumbbellShoulderPress: "Dumbbell Shoulder Press",
  alternatingDumbbellShoulderPress: "Alternating Dumbbell Shoulder Press",
  smithMachineShoulderPress: "Shoulder Press (Smith Machine)",
  machineShoulderPress: "Shoulder Press (Machine)",
  lateralRaises: "Lateral Raises",
  frontDumbbellRaises: "Dumbbell Front Raises",
  rearDeltFly: "Rear Delt Fly",
  reversePecDec: "Reverse Pec Dec Fly",
  shrugsBarbell: "Barbell Shrugs",
  shrugsDumbbell: "Dumbbell Shrugs",
  facePulls: "Face Pulls",
  arnoldPress: "Arnold Press",
  uprightRow: "Upright Row",
  militaryPress: "Military Press",
  seatedBentOverRearDeltRaise: "Seated Bent-Over Rear Delt Raise",
  standingDumbbellFly: "Standing Dumbbell Fly",
  egyptianLatRaise: "Egyptian Lat Raise",
  bentOverRearDeltRow: "Dumbbell Bent-over Rear Delt Row",

  //Triceps
  tricepPulldownRope: "Tricep Push-down (Rope)",
  tricepPushdownStraightbar: "Straight Bar Tricep Push-down",
  tricepPushdownVBar: "Tricep Push-down (V Bar)",
  skullCrushersEZBar: "EZ Bar Skull Crushers",
  dumbbellTricepExtension: "Dumbbell Tricep Extension",
  tricepDips: "Tricep Dips",
  closeGripBenchPress: "Close-Grip Bench Press",
  cableTricepKickback: "Cable Kickbacks",
  dumbbellTricepKickbacks: "Dumbbell Kickbacks",
  overheadTricepExtension: "Overhead Tricep Extension",
  closeGripPushup: "Close Position Pushup",
  singleArmDumbbellTricepExtension: "Single Arm Dumbbell Tricep Extension",

  // Biceps
  bicepCurlBarbell: "Barbell Bicep Curl",
  bicepCurlDumbbell: "Dumbbell Bicep Curl",
  twentyOnesBarbell: "21's Barbell Curl",
  twentyOnesDumbbell: "21's Dumbbell Curl",
  seatedInclineDumbbellCurl: "Seated Incline Curl (Dumbbells)",
  bayesianCableCurl: "Bayesian Cable Curl",
  hammerCurlDumbbell: "Dumbbell Hammer Curl",
  preacherCurlBarbell: "Barbell Preacher Curl",
  wideGripBarbellCurl: "Wide-Grip Barbell Curl",
  concentrationCurls: "Concentration Curls",
  zottmanCurl: "Zottman Curl",
  cableBicepCurl: "Cable Bicep Curl",

  // Abs
  crunches: "Crunches",
  crunchesWeighted: "Weighted Crunches",
  abCrunchMachine: "Ab Crunch Machine",
  legRaises: "Leg Raises",
  plank: "Plank",
  russianTwist: "Russian Twist",
  hangingLegRaise: "Hanging Leg Raise",
  bicycleCrunches: "Bicycle Crunches",
  mountainClimbers: "Mountain Climbers",
  jackknifeSitup: "Jackknife Sit-Up",
  abWheelRollout: "Ab Wheel Rollout",
  cableCrunch: "Cable Crunch",
  cocoon: "Cocoon",
};
